### ISSUE TITLE
I want people to be able to learn and purchase NANO all in one. 

### ISSUE THREAD

**Issue by santiesque** [formsend/nano.to#1]
For the folks new to NANO landing on your checkout.

What are some options? 

nano.org, crypto.com?

**Comment by filipesmedeiros** [comment]
Send them to nano.org, yeah. Maybe directly to some marketing material like introduction videos? Or maybe create a simple one with the most important bullet points?

**Comment by santiesque** [comment]
I thought about hosting a page on nano.to to explain the tech, but I'd prefer if it linked out to a more 'official' source. 

Kinda wish Nano Foundation had more layman websites.

I'll leave 'nano.org' for now.
