### ISSUE TITLE
Whats a good rep for the main nano.to address?

### ISSUE THREAD

**Issue by santiesque** [formsend/nano.to#2]

**Comment by zQueal** [comment]
I highly recommend using Nalli:

> nano_3zapp5z141qpjipsb1jnjdmk49jwqy58i6u6wnyrh6x7woajeyme85shxewt

**Comment by santiesque** [comment]
Thanks will check it out.

P.s - We are Launching our own Rep Node in the next few months. Can you say 999.999% Uptime ;)

Thanks!

**Comment by santiesque** [comment]
Ok, going with Nalli

For the next few months.
