### ISSUE TITLE
Auto check payment

### ISSUE THREAD

**Issue by dderooy** [formsend/nano.to#8]
Add logic to auto check payment. A polling method with backoff factor and max retry would work. If max retries are exceeded then revert to manual check payment button.

**Comment by santiesque** [comment]
The Checkout page redirects to the configured 'success_url' after a short delay, on success.

I think it would be bad UX to redirect the Checkout page right after payment.  

There's a human factor to 'Clicking something when you're ready and waiting for it complete'
